### PR TITLE
Promises support

### PR DESCRIPTION
**Pull request by catalint**
An attempt at removing callbacks and relying on promises.

No major refactoring was needed for tests, just removing callbacks & relying on promise chain

notable changes for client
--- 
none

notable changes for policy
---
- the callback was binded to process.domain, with promises I could't find an analog, and from what I've seen node `domain` is deprecated, my best guess is that using promises doesn't need the use case callback needed when binding 
- Promise.resolve() accepts only one argument, so:
 -  `policy.get(key)`)
     - it resolved the cached / generated value
     - if a stale timeout or any error that doesn't invalidate the cache occures, the cached item is sent via `resolve()`
     - if any other unrecoverable error , it calls `reject(err)`
 - `policy.get(key,{full:true})`
    - it resolved an object with the previously sent arguments (err, value, cached, report)
    - if err is present and not undefined/null , then it it rejected with the same object, even if the cached value may be still valid)

todos
---
- hapi support for this in other repos
- a major version increment will be needed

what are your thoughts on this?

### CODE REVIEW

**Comment by catalint** [comment]
I'll change the tests a bit to better handle promises, will need to upgrade to lab 10 (it's 8 right now in package.json)

**Comment by hueniverse** [comment]
No chance I will be removing callbacks. I am open to offering a secondary promises support same way I did in hapi. That is, callback is the default and how the system is designed while promises support is added as syntactic sugar.

Note that I am not anti-promises or am passing judgement on people who likes to use them. It's a perfectly valid design choice. It's just not my design choice.

**Comment by catalint** [comment]
We can have both worlds!

Expect this PR to be updated in a couple of days.

**Comment by catalint** [comment]
updated to support both promises & callbacks, no change in logic was done to callbacks , callback tests ran without any changes

added tests for promises , added promise sections in README.MD after the callback ones

**Comment by Marsup** [comment]
Maybe it's time we re-discuss putting https://github.com/hapijs/hapi/blob/master/lib/promises.js into hoek.

**Comment by hueniverse** [comment]
@Marsup someone should just do it and PR the move on hapi.

**Comment by catalint** [comment]
hi @hueniverse have you gotten the chance to look over this? if you require any changes I'm more than happy to do them. thanks!

**Comment by hueniverse** [comment]
I'd like to see the pattern used by hapi moved to hoek and then used here. Also, do we really need to c/p the entire readme?

**Comment by hueniverse** [comment]
As I said back in April, the only way I am going to support promises is using the same pattern I used in hapi. This would require moving that utility to hoek. I might look into that but it's low on my list.

**Comment by juanjoLenero** [comment]
Can this be reconsidered now that https://github.com/hapijs/hoek/issues/176 met a dead end?

**Pull request closed without merging**
